language: go

go:
  - 1.3
  - 1.4
  - 1.5
  - tip

install:
 - go get ./...
 - go get -u github.com/golang/lint/golint

script: 
 - go vet ./...
 - go test -v -cpu=1,2,4 .
 - go test -v -cpu=1,2,4 -short -race .
 - go test -tags=noasm -v -cpu=1,2,4 -short -race .
 - go build examples/simple-decoder.go
 - go build examples/simple-encoder.go
 - go build examples/stream-decoder.go
 - go build examples/stream-encoder.go
 - diff <(gofmt -d .) <("")
 - diff <(golint ./...) <("")
