language: go

os:
  - linux
  - os
  - windows

arch:
  - amd64
  - arm64
  - ppc64le

go:
  - 1.12.x
  - 1.13.x
  - 1.14.x
  - master

install:
 - go get ./...

script: 
 - go vet ./...
 - go test -v -cpu=1,2,4 .
 - go test -v -cpu=1,2,4 -short -race .
 - go test -no-avx512
 - go test -no-avx512 -no-avx2
 - go test -tags=noasm -v -cpu=1,4 -short -race .
 - go build examples/simple-decoder.go
 - go build examples/simple-encoder.go
 - go build examples/stream-decoder.go
 - go build examples/stream-encoder.go
 - diff <(gofmt -d .) <("")
 - GOARCH=386 GOOS=linux go build .

matrix:
  allow_failures:
    - go: 'master'
  fast_finish: true
